application:
  client-origin-url: ${CLIENT_ORIGIN_URL}

spring:
  data:
    mongodb:
      database: "bfi"
      uri: ${AUTHENTICATED_MONGO_URI}
server:
  error:
    include-message: always
bfi:
  s3:
    bucket: "bfinance-resources"
    receipt-prefix: "receipts"
